version: "3"
services:
  app:
    container_name: photogallery
    restart: always
    build: .
    ports:
      - "80:3004"
    links:
       - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db
    ports:
      - "27017:27017"